Avantica/Controllers/PropertiesController.cs
// ----------------------------------------------------------------------------
// <copyright file="PropertiesController.cs" company="Encora S.A">
//     COPYRIGHT(C) 2020, Encora S.A
// </copyright>
// <author>Johan Ospina Nuñez</author>
// <email>jospina@Encora.com.</email>
// <summary>Properties controller</summary>
// ----------------------------------------------------------------------------

using Avantica.Data;
using Avantica.Models.WebApplication3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Polly;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Properties = Avantica.Models.Properties;

namespace Avantica.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly AvanticaContext context;

        public PropertiesController(AvanticaContext context)
        {
            this.context = context;
        }

        // GET: Properties
        /// <summary>
        /// Get to bring service data
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            var respuesta = await CallToConsumeWebService().ConfigureAwait(false);
            List<Properties> datos = new List<Properties>();

            foreach (var item in respuesta.properties)
            {
                string test = item.financial?.listPrice;
                string test2 = item.lease?.leaseSummary?.monthlyRent;
                double? result = (Convert.ToDouble(test2) * 12) / Convert.ToDouble(test);
                Properties tabla = new Properties
                {
                    Address = item.address?.address1,
                    Gross_Yield = result?.ToString(),
                    Year_Built = item.physical?.yearBuilt,
                    List_Price = test?.ToString(),
                    Monthly_Rent = test2 != null ? test2.ToString() : null
                };

                datos.Add(tabla);
            }

            return View(datos);
        }

        /// <summary>
        /// Process to consume web service
        /// </summary>
        /// <returns></returns>
        private async Task<Application> CallToConsumeWebService()
        {
            Uri url = new Uri("https://samplerspubcontent.blob.core.windows.net/public/properties.json");

            var response = await ConsumeServiceGetAsync(url).ConfigureAwait(false);

            if (!string.IsNullOrEmpty(response))
            {
                return JsonConvert.DeserializeObject<Application>(response);
            }

            return null;
        }

        /// <summary>
        /// Consume External Service
        /// </summary>
        /// <param name="url"></param>
        /// <returns></returns>
        private async Task<string> ConsumeServiceGetAsync(Uri url)
        {
            using var httpClient = new HttpClient();

            using var response = await Policy.HandleResult<HttpResponseMessage>(message => !message.IsSuccessStatusCode)
                  .WaitAndRetryAsync(3, i => TimeSpan.FromSeconds(2), (result, timeSpan, retryCount, context) => { })
                  .ExecuteAsync(() => httpClient.GetAsync(url));

            return await response.Content.ReadAsStringAsync().ConfigureAwait(false);
        }

        // GET: Properties/Details/5
        /// <summary>
        /// Process that shows info insert in database
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(string id)
        {
            return View(await context.Properties.ToListAsync());
        }

        // GET: Properties/Create
        /// <summary>
        /// Process to load service information in View
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Create(string id)
        {
            var respuesta = await CallToConsumeWebService().ConfigureAwait(false);
            List<Properties> datos = new List<Properties>();
            Properties properties = null;

            foreach (var item in respuesta.properties)
            {
                if (item.address.address1 == id)
                {
                    string test = item.financial?.listPrice;
                    string test2 = item.lease?.leaseSummary?.monthlyRent;
                    double? result = (Convert.ToDouble(test2) * 12) / Convert.ToDouble(test);
                    Properties tabla = new Properties
                    {
                        Address = item.address?.address1,
                        Gross_Yield = result?.ToString(),
                        Year_Built = item.physical?.yearBuilt,
                        List_Price = test?.ToString(),
                        Monthly_Rent = test2 != null ? test2.ToString() : null
                    };

                    properties = tabla;
                }
            }

            if (properties == null)
            {
                return NotFound();
            }

            return View(properties);
        }

        // POST: Properties/Create
        /// <summary>
        /// method to insert information in dtabase
        /// </summary>
        /// <param name="properties"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Properties properties)
        {
            var exist = context.Properties.FirstOrDefault(x => x.Address == properties.Address);

            if (exist == null)
            {
                if (ModelState.IsValid)
                {
                    context.Add(properties);
                    await context.SaveChangesAsync();
                    return RedirectToAction(nameof(Details));
                }
            }
            return View(properties);
        }

        // GET: Properties/Edit/5
        /// <summary>
        /// method to load information in form to update
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var properties = context.Properties.FirstOrDefault(x => x.Address == id);

            double? result = Convert.ToDouble(properties.Monthly_Rent) * 12 / Convert.ToDouble(properties.List_Price);

            properties.Gross_Yield = result.ToString();

            if (properties == null)
            {
                return NotFound();
            }

            return View(properties);
        }

        // POST: Properties/Edit/5
        /// <summary>
        /// method to update database information.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="properties"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Properties properties)
        {
            if (id != properties.Address)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(properties);
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropertiesExists(properties.Address))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details));
            }
            return View(properties);
        }

        /// <summary>
        /// method to check if property exists
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool PropertiesExists(string id)
        {
            return context.Properties.Any(e => e.Address == id);
        }
    }
}

Avantica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Avantica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <!-- Default theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css" />
    <!-- Semantic UI theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/semantic.min.css" />
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/bootstrap.min.css" />

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Properties" asp-action="Index">Avantica</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Avantica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <!-- JavaScript -->
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>